export const CUSTOMER_REQUEST = 'CUSTOMER_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const POLICIES_REQUEST = 'POLICIES_REQUEST';
export const POLICIES_RESPONSE = 'POLICIES_RESPONSE';
export const POLICIES_FAILURE = 'POLICIES_FAILURE';

export const ACCOUNTS_REQUEST = 'ACCOUNTS_REQUEST';
export const ACCOUNTS_RESPONSE = 'ACCOUNTS_RESPONSE';
export const ACCOUNTS_FAILURE = 'ACCOUNTS_FAILURE';
