export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_RESPONSE = 'USER_RESPONSE';
export const USER_FAILURE = 'USER_FAILURE';

export const POLICIES_REQUEST = 'POLICIES_REQUEST';
export const POLICIES_RESPONSE = 'POLICIES_RESPONSE';
export const POLICIES_FAILURE = 'POLICIES_FAILURE';

export const ACCOUNTS_REQUEST = 'ACCOUNTS_REQUEST';
export const ACCOUNTS_RESPONSE = 'ACCOUNTS_RESPONSE';
export const ACCOUNTS_FAILURE = 'ACCOUNTS_FAILURE';

export const TIMELINE_EVENTS_REQUEST = 'TIMELINE_EVENTS_REQUEST';
export const TIMELINE_EVENTS_RESPONSE = 'TIMELINE_EVENTS_RESPONSE';
export const TIMELINE_EVENTS_FAILURE = 'TIMELINE_EVENTS_FAILURE';

export const AGENT_REQUEST = 'AGENT_REQUEST';
export const AGENT_RESPONSE = 'AGENT_RESPONSE';
export const AGENT_FAILURE = 'AGENT_FAILURE';

export const INIT_FROM_LOCAL_STORAGE = 'INIT_FROM_LOCAL_STORAGE';

export const CONFIG_REQUEST = 'CONFIG_REQUEST';
export const CONFIG_RESPONSE = 'CONFIG_RESPONSE';
export const CONFIG_FAILURE = 'CONFIG_FAILURE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
